
export const tags: string[] = [
    'independent',
    'nonprofit',
    'noncommercial',
    'no_ads',
    'search_engine',
    'retro',
    'personal_homepage',
    'music_artist',
    'guestbook',
    'link_hub',
    'autoplay_audio',
    'gif_graphics',
    'donation_link',
    'user_generated_content',
    'public_service',
    'updated_2024',
    'updated_2026',
    'minimal_javascript',
    'vanilla',
    'pure_vanilla',
    'jquery',
    'webgl',
    'pixel_art',
    'browser_games',
    'portal_style',
    'retro_gaming',
    'game_database',
    'fansite',
    'serial_experiments_lain',
    'anime_inspired',
    'cyberpunk',
    'archive',
    'abandoned',
    'community',
    'experimental',
    'indie_web'
];

export const posts: string[][] = [
    ['/dev/thumbs/nickhz.live_cyber.jpg', 'https://nickhz.live/cyber'],
    ['/dev/thumbs/ytoo.org.jpg', 'https://ytoo.org'],
    ['/dev/thumbs/www.cameronsworld.net.jpg', 'https://www.cameronsworld.net'],
    ['/dev/thumbs/web.archive.org.jpg', 'https://web.archive.org'],
    ['/dev/thumbs/virtualself.co.jpg', 'https://virtualself.co'],
    ['/dev/thumbs/everskies.com.jpg', 'https://everskies.com'],
    ['/dev/thumbs/forum.melonland.net.jpg', 'https://forum.melonland.net'],
    ['/dev/thumbs/oyaswmi.net.jpg', 'https://oyaswmi.net'],
    ['/dev/thumbs/www.girlsgogames.com.jpg', 'https://www.girlsgogames.com'],
    ['/dev/thumbs/lain.angelic-trust.net_wired.html.jpg', 'https://lain.angelic-trust.net/wired.html'],
    ['/dev/thumbs/www.mercurialworld.com.jpg', 'https://www.mercurialworld.com'],
    ['/dev/thumbs/psxdatacenter.com.jpg', 'https://psxdatacenter.com'],
    ['/dev/thumbs/espy.world.jpg', 'https://espy.world'],
    ['/dev/thumbs/activetheory.net.jpg', 'https://activetheory.net'],
    ['/dev/thumbs/corru.observer.jpg', 'https://corru.observer'],
    ['/dev/thumbs/classic.systemspace.network.jpg', 'https://classic.systemspace.network'],
    ['/dev/thumbs/eieio.games.jpg', 'https://eieio.games'],
    ['/dev/thumbs/neocities.org.jpg', 'https://neocities.org'],
    ['/dev/thumbs/nekoweb.org.jpg', 'https://nekoweb.org'],
    ['/dev/thumbs/www.tubcat.com.jpg', 'https://www.tubcat.com'],
    ['/dev/thumbs/brisray.com_web_webring-list.htm.jpg', 'https://brisray.com/web/webring-list.htm']
];
